config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :mixtapes, only: [ :index ]
  resources :videos, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_class
    devise_mapping.to
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image']
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= image_url(meta_image) %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META['twitter_account'] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META['twitter_account'] %>">
    <meta name="twitter:image:src" content="<%= image_url(meta_image) %>">

    <!-- Google+ Schema.org markup -->
    <meta itemprop="name" content="<%= meta_title %>">
    <meta itemprop="description" content="<%= meta_description %>">
    <meta itemprop="image" content="<%= image_url(meta_image) %>">

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>

    <%= render 'shared/favicons' %>
  </head>
  <body>
    <% if current_page?(root_path) %>
      <%= render 'shared/navbar-home' %>
    <% else %>
      <%= render 'shared/navbar' %>
    <% end %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_favicons.html.erb
<%= favicon_link_tag 'favicons/apple-icon-57x57.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '57x57' %>
<%= favicon_link_tag 'favicons/apple-icon-60x60.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '60x60' %>
<%= favicon_link_tag 'favicons/apple-icon-72x72.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '72x72' %>
<%= favicon_link_tag 'favicons/apple-icon-76x76.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '76x76' %>
<%= favicon_link_tag 'favicons/apple-icon-114x114.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '114x114' %>
<%= favicon_link_tag 'favicons/apple-icon-120x120.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '120x120' %>
<%= favicon_link_tag 'favicons/apple-icon-144x144.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '144x144' %>
<%= favicon_link_tag 'favicons/apple-icon-152x152.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '152x152' %>
<%= favicon_link_tag 'favicons/apple-icon-180x180.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '180x180' %>
<%= favicon_link_tag 'favicons/android-icon-192x192.png', rel: 'icon', type: 'image/png', sizes: '192x192' %>
<%= favicon_link_tag 'favicons/favicon-32x32.png', rel: 'icon', type: 'image/png', sizes: '32x32' %>
<%= favicon_link_tag 'favicons/favicon-96x96.png', rel: 'icon', type: 'image/png', sizes: '96x96' %>
<%= favicon_link_tag 'favicons/favicon-16x16.png', rel: 'icon', type: 'image/png', sizes: '16x16' %>
<link rel="manifest" href="favicons/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="favicons/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/shared/_flashes-home.html.erb
<% if notice %>
  <div class="message" data-component="message">
    <%= notice %>
    <span class="close small"></span>
  </div>
<% end %>

<% if alert %>
  <div class="message warning" data-component="message" role="alert">
    <h5>Warning</h5>
    <%= alert %>
    <span class="close small"></span>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">

  <div class="footer-left">
    <div class="container-networks">
      <div class="row">
        <div class="col col-3">
          <%= link_to "https://www.youtube.com/user/GetTheSound2", target: :_blank do %>
            <i class="fa fa-youtube" aria-hidden="true"></i>
          <% end %>
        </div>
        <div class="col col-3">
          <%= link_to "https://www.facebook.com/GetTheSound", target: :_blank do %>
            <i class="fa fa-facebook" aria-hidden="true"></i>
          <% end %>
        </div>
        <div class="col col-3">
          <%= link_to "https://open.spotify.com/user/125882460/playlist/6GVH2qReMQOmcBKT2tuTao?play=true&utm_source=open.spotify.com&utm_medium=open&play=true", target: :_blank do %>
            <i class="fa fa-spotify" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col col-3 offset-3">
          <%= link_to "https://www.instagram.com/getthesound/", target: :_blank do %>
            <i class="fa fa-instagram" aria-hidden="true"></i>
          <% end %>
        </div>
        <div class="col col-3">
          <%= link_to "https://twitter.com/_GetTheSound", target: :_blank do %>
            <i class="fa fa-twitter" aria-hidden="true"></i>
          <% end %>
        </div>
        <div class="col col-3">
          <%= link_to "https://soundcloud.com/getthesound2", target: :_blank do %>
            <i class="fa fa-soundcloud" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="footer-middle">
    <div class="footer-list">
      <ul>
        <li class=footer-list-title>
          About
        </li>
        <li class="footer-list-item">
          <%= link_to "#" do %>
            Events
          <% end %>
        </li>
        <li class="footer-list-item">
          <%= link_to "#" do %>
            Our project
          <% end %>
        </li>
        <li class="footer-list-item">
          <%= link_to "#" do %>
            Genese
          <% end %>
        </li>
      </ul>
    </div>
    <div class="footer-list">
      <ul>
        <li class=footer-list-title>
          Contact us
        </li>
        <li class="footer-list-item">
          <%= link_to "#" do %>
            Label
          <% end %>
        </li>
        <li class="footer-list-item">
          <%= link_to "#" do %>
            Broadcast channel
          <% end %>
        </li>
        <li class="footer-list-item">
          <%= link_to "#" do %>
            Other enquiries
          <% end %>
        </li>
      </ul>
    </div>
  </div>

  <div class="footer-right">
    <div class="footer-right-stretch">
      <div class="footer-image">
        <%= image_tag asset_path("logo_white.png") %>
      </div>
      <div class="footer-subscribe">
        <p>SUBSCRIBE TO OUR MAILING LIST</p>
        <form class="form form-inline">
          <div class="form-item">
            <input type="email" name="email" placeholder="your email" class="small w50 subscribe-mail">
            <input type="submit" name="subscribe" value="Subscribe" class="small w50 button secondary outline">
          </div>
        </form>
      </div>
    </div>
  </div>

</footer>

app/views/shared/_navbar-home.html.erb
<nav class="navbar-home">

  <div class="navbar-left">
    <%= image_tag asset_path("logo_white.png") %>
  </div>

  <div class="navbar-middle">

    <!-- Search -->
    <div class="navbar-item" id="search-wrapper">
      <i class='material-icons md-18'>search</i>
    </div>

  </div>

  <div class="navbar-right">

    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-item">
        <div id="navbar-dropdown">
          <!-- Dropdown toggle -->
          <%= link_to "#", id: "user-avatar", "data-component" => "dropdown", "data-target" => "#dropdown" do %>
            <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
            <%= image_tag avatar_url, class: "avatar-large" %>
          <% end %>

          <!-- Notifications -->
          <%#= link_to "#", class: "badge-container" do %>
            <!--<span class="badge badge-blue">3</span>-->
          <%# end %>

        <div class="dropdown hide" id="dropdown">
            <a href="" class="close show-sm"></a>
            <ul>
              <li>
                <%= link_to "" do %>
                  <i class='material-icons md-18'>account_circle</i> My profile
                <% end %>
              </li>
              <li>
                <%= link_to "" do %>
                  <i class='material-icons md-18'>turned_in</i> My bookmarks
                <% end %>
              </li>
              <li>
                <%= link_to "" do %>
                  <i class='material-icons md-18'>settings</i> Settings
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class='material-icons md-18'>exit_to_app</i> <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>

        </div>
      </div>

    <% else %>
      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), "#", "data-component" => "modal", "data-target" => "#login-modal", class: "navbar-item upper" %>
    <% end %>

    <!-- Navigation links -->
    <%= link_to t(".top_call_to_action", default: "Shop"), "#", class: "navbar-item upper hide-sm" %>
    <%= link_to t(".top_call_to_action", default: "Label"), "#", class: "navbar-item upper hide-sm" %>
    <%= link_to t(".top_call_to_action", default: "Mixtapes"), mixtapes_path, class: "navbar-item upper hide-sm" %>

  </div>

</nav>
<div id="login-modal" class="modal-box hide">
    <div class="modal">
        <span class="close"></span>
        <div class="modal-header"><%= t(".sign_in", default: "Login") %></div>
        <div class="modal-body">
          <%= render 'devise/sessions/login-form' %>
        </div>
    </div>
</div>

app/views/shared/_navbar-wagon.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar">

  <div class="navbar-left">
    <%= link_to root_path do %>
      <%= image_tag asset_path("logo_black.png") %>
    <% end %>

  </div>

  <div class="navbar-middle">

    <!-- Search -->
    <div class="navbar-item" id="search-wrapper">
      <i class='material-icons md-18'>search</i>
    </div>

  </div>

  <div class="navbar-right">

    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-item">
        <div id="navbar-dropdown">
          <!-- Dropdown toggle -->
          <%= link_to "#", id: "user-avatar", "data-component" => "dropdown", "data-target" => "#dropdown" do %>
            <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
            <%= image_tag avatar_url, class: "avatar-large" %>
          <% end %>

          <!-- Notifications -->
          <%#= link_to "#", class: "badge-container" do %>
            <!--<span class="badge badge-blue">3</span>-->
          <%# end %>

        <div class="dropdown hide" id="dropdown">
            <a href="" class="close show-sm"></a>
            <ul>
              <li>
                <%= link_to "" do %>
                  <i class='material-icons md-18'>account_circle</i> My profile
                <% end %>
              </li>
              <li>
                <%= link_to "" do %>
                  <i class='material-icons md-18'>turned_in</i> My bookmarks
                <% end %>
              </li>
              <li>
                <%= link_to "" do %>
                  <i class='material-icons md-18'>settings</i> Settings
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class='material-icons md-18'>exit_to_app</i> <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>

        </div>
      </div>

    <% else %>
      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), "#", "data-component" => "modal", "data-target" => "#login-modal", class: "navbar-item upper" %>
    <% end %>

    <!-- Navigation links -->
    <%= link_to t(".top_call_to_action", default: "Shop"), "#", class: "navbar-item upper hide-sm" %>
    <%= link_to t(".top_call_to_action", default: "Label"), "#", class: "navbar-item upper hide-sm" %>
    <%= link_to t(".top_call_to_action", default: "Mixtapes"), mixtapes_path, class: "navbar-item upper hide-sm" %>

  </div>

</nav>
<div id="login-modal" class="modal-box hide">
    <div class="modal">
        <span class="close"></span>
        <div class="modal-header"><%= t(".sign_in", default: "Login") %></div>
        <div class="modal-body">
          <%= render 'devise/sessions/login-form' %>
        </div>
    </div>
</div>